"""RCA Report Generator — portfolio demo for freelance Service 1."""

from __future__ import annotations

from datetime import date
from io import BytesIO

import streamlit as st
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


def build_markdown_report(data: dict[str, str]) -> str:
    """Render RCA report as Markdown."""
    lines = [
        f"# Root Cause Analysis Report",
        "",
        f"**Document ID:** {data['doc_id']}",
        f"**Date:** {data['report_date']}",
        f"**Prepared by:** {data['prepared_by']}",
        f"**Status:** {data['status']}",
        "",
        "## 1. Executive Summary",
        data["executive_summary"] or "_Not provided._",
        "",
        "## 2. Issue Information",
        "",
        "| Field | Detail |",
        "|-------|--------|",
        f"| Equipment | {data['equipment_name']} |",
        f"| Customer / Site | {data['customer_site']} |",
        f"| Severity | {data['severity']} |",
        f"| Symptom | {data['symptom']} |",
        "",
        "## 3. Problem Description",
        data["problem_description"] or "_Not provided._",
        "",
        "## 4. Environment",
        data["environment"] or "_Not provided._",
        "",
        "## 5. Test Results & Evidence",
        data["test_results"] or "_Not provided._",
        "",
        "## 6. Root Cause Analysis",
        "",
        "### Root cause",
        data["root_cause"] or "_Not provided._",
        "",
        "### Contributing factors",
        data["contributing_factors"] or "_None listed._",
        "",
        "## 7. Corrective Actions",
        data["corrective_actions"] or "_Not provided._",
        "",
        "## 8. Verification",
        data["verification"] or "_Not provided._",
        "",
        "## 9. Preventive Recommendations",
        data["preventive_recommendations"] or "_Not provided._",
        "",
        "---",
        "_Generated by RCA Report Generator — Joonha Lee Engineering Documentation Services_",
    ]
    return "\n".join(lines)


def build_docx_report(data: dict[str, str]) -> bytes:
    """Render RCA report as DOCX bytes."""
    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

    title = doc.add_heading("Root Cause Analysis Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.add_run(f"Document ID: {data['doc_id']}\n").bold = True
    meta.add_run(f"Date: {data['report_date']}\n")
    meta.add_run(f"Prepared by: {data['prepared_by']}\n")
    meta.add_run(f"Status: {data['status']}")

    sections = [
        ("1. Executive Summary", data["executive_summary"]),
        ("2. Issue Information", None),
        ("3. Problem Description", data["problem_description"]),
        ("4. Environment", data["environment"]),
        ("5. Test Results & Evidence", data["test_results"]),
        ("6. Root Cause Analysis", data["root_cause"]),
        ("7. Corrective Actions", data["corrective_actions"]),
        ("8. Verification", data["verification"]),
        ("9. Preventive Recommendations", data["preventive_recommendations"]),
    ]

    for heading, body in sections:
        doc.add_heading(heading, level=1)
        if heading == "2. Issue Information":
            table = doc.add_table(rows=4, cols=2)
            table.style = "Table Grid"
            rows = [
                ("Equipment", data["equipment_name"]),
                ("Customer / Site", data["customer_site"]),
                ("Severity", data["severity"]),
                ("Symptom", data["symptom"]),
            ]
            for i, (label, value) in enumerate(rows):
                table.rows[i].cells[0].text = label
                table.rows[i].cells[1].text = value
            if data["contributing_factors"]:
                doc.add_heading("Contributing factors", level=2)
                doc.add_paragraph(data["contributing_factors"])
        elif body:
            para = doc.add_paragraph(body)
            for run in para.runs:
                run.font.size = Pt(11)

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def load_sample_data() -> dict[str, str]:
    """Pre-fill form with portfolio sample (satellite terminal link loss)."""
    return {
        "doc_id": "RCA-2026-SAT-0142",
        "report_date": str(date.today()),
        "prepared_by": "Joonha Lee",
        "status": "Closed — corrective action verified",
        "equipment_name": "LEO Maritime VSAT Terminal (Model MTX-4500)",
        "customer_site": "[Anonymized] — Offshore support vessel",
        "severity": "High — mission communication impact",
        "symptom": "Intermittent link loss; modem re-registration every 15–45 min",
        "problem_description": (
            "The terminal established initial satellite lock but lost connectivity "
            "repeatedly during vessel operation. NMS logs showed MODEM_REREG events "
            "without RF obstruction alarms. Events increased during heavy seas and "
            "main-engine load changes."
        ),
        "environment": (
            "Open sea trial area; roll ±12°, pitch ±8°. Ship 24 VDC panel Branch CB-14. "
            "Ambient 28–34 °C; enclosure internal peak 42 °C. Installation age 6 weeks."
        ),
        "test_results": (
            "Log review: LINK_LOST preceded by VIN_DIP 21.8–22.1 V.\n"
            "Measurements: steady 24.2 V; load-step dip to 21.6 V; ground 4.8 Ω (limit <1 Ω).\n"
            "Classification: power integrity + grounding (installation-related)."
        ),
        "root_cause": (
            "Inadequate DC input filtering allowed transient undervoltage during ship load "
            "steps, triggering modem reset. Contributing factor: marginal RF ground strap at radome base."
        ),
        "contributing_factors": "SAT checklist did not include load-step power test or ground ohmmeter check.",
        "corrective_actions": (
            "CA-01: Install marine-rated DC filter at modem input.\n"
            "CA-02: Replace and torque ground strap; verify <1 Ω.\n"
            "CA-03: Update SAT checklist with power dip test."
        ),
        "verification": (
            "48 h continuous link test: 0 unplanned dropouts — Pass.\n"
            "Power dip test: min 23.1 V at modem — Pass.\n"
            "Ground resistance: 0.6 Ω — Pass."
        ),
        "preventive_recommendations": (
            "Add load-step DC holdup test to maritime SAT procedures. "
            "Specify maximum ground resistance in installation work instructions."
        ),
        "executive_summary": (
            "Intermittent link loss during sea trials was traced to DC input transients and "
            "marginal grounding. After filter installation and ground rework, 48-hour link "
            "stability test passed with zero dropouts."
        ),
    }
